### ISSUE TITLE
bug in fvec4  horizontal_max_index function 

### ISSUE THREAD

**Issue by slimailisi** [jpilet/polyora#1]
The for loop condition in this line  
```
for (int i=1; i<3; i++)
```
should be 
```
for (int i=1; i<4; i++)
```

The original implemetation will cause a bug when the 3rd element is max.

https://github.com/jpilet/polyora/blob/dfdb94a6269afb3acae7b28284e4af789fbfaeba/polyora/fvec4.h#L78

**Comment by jpilet** [comment]
many thanks for the bug report @slimailisi
